#!/bin/bash

set -e

if [[ -z "$1" ]]; then
  echo "Usage: script/build PROJECTNAME"
  exit 1
fi

proj="$1"
shift

docker build -f "${proj}/Dockerfile" -t "cocov/${proj}:$(cat "${proj}/VERSION" | head -n 1)" $@ .
docker push "cocov/${proj}:$(cat "${proj}/VERSION" | head -n 1)"

