package common

import "github.com/cocov-ci/go-plugin-kit/cocov"

// GoCriticCheckers represents the set of linters used by go-critic
// TODO: Take a look at each checker and confirm whether it suits Cocov's issue
//
//	kinds or must change.
//
// references for each checker can be found at:
// https://go-critic.com/overview.html#checkers
var GoCriticCheckers = map[string]cocov.IssueKind{
	// Current go-critic classification: Diagnostic
	"appendAssign":          cocov.IssueKindBug,
	"argOrder":              cocov.IssueKindBug,
	"badCall":               cocov.IssueKindBug,
	"badCond":               cocov.IssueKindBug,
	"badLock":               cocov.IssueKindBug,
	"badRegexp":             cocov.IssueKindBug,
	"builtinShadowDecl":     cocov.IssueKindBug,
	"caseOrder":             cocov.IssueKindBug,
	"codegenComment":        cocov.IssueKindBug,
	"commentedOutCode":      cocov.IssueKindBug,
	"deprecatedComment":     cocov.IssueKindBug,
	"dupArg":                cocov.IssueKindBug,
	"dupBranchBody":         cocov.IssueKindBug,
	"dupCase":               cocov.IssueKindBug,
	"dupSubExpr":            cocov.IssueKindBug,
	"emptyDecl":             cocov.IssueKindBug,
	"evalOrder":             cocov.IssueKindBug,
	"exitAfterDefer":        cocov.IssueKindBug,
	"externalErrorReassign": cocov.IssueKindBug,
	"filepathJoin":          cocov.IssueKindBug,
	"flagDeref":             cocov.IssueKindBug,
	"flagName":              cocov.IssueKindBug,
	"mapKey":                cocov.IssueKindBug,
	"nilValReturn":          cocov.IssueKindBug,
	"offBy1":                cocov.IssueKindBug,
	"regexpPattern":         cocov.IssueKindBug,
	"returnAfterHttpError":  cocov.IssueKindBug,
	"sloppyReassign":        cocov.IssueKindBug,
	"sloppyTypeAssert":      cocov.IssueKindBug,
	"sortSlice":             cocov.IssueKindBug,
	"sprintfQuotedString":   cocov.IssueKindBug,
	"sqlQuery":              cocov.IssueKindBug,
	"suspiciousSorting":     cocov.IssueKindBug,
	"syncMapLoadAndDelete":  cocov.IssueKindBug,
	"truncateCmp":           cocov.IssueKindBug,
	"unnecessaryDefer":      cocov.IssueKindBug,
	"weakCond":              cocov.IssueKindBug,

	// Current go-critic classification: Style
	"assignOp":              cocov.IssueKindStyle,
	"boolExprSimplify":      cocov.IssueKindStyle,
	"builtinShadow":         cocov.IssueKindStyle,
	"captLocal":             cocov.IssueKindStyle,
	"commentFormatting":     cocov.IssueKindStyle,
	"commentedOutImport":    cocov.IssueKindStyle,
	"defaultCaseOrder":      cocov.IssueKindStyle,
	"deferUnlambda":         cocov.IssueKindStyle,
	"docStub":               cocov.IssueKindStyle,
	"dupImport":             cocov.IssueKindStyle,
	"elseif":                cocov.IssueKindStyle,
	"emptyFallthrough":      cocov.IssueKindStyle,
	"emptyStringTest":       cocov.IssueKindStyle,
	"exposedSyncMutex":      cocov.IssueKindStyle,
	"hexLiteral":            cocov.IssueKindStyle,
	"httpNoBody":            cocov.IssueKindStyle,
	"ifElseChain":           cocov.IssueKindStyle,
	"importShadow":          cocov.IssueKindStyle,
	"initClause":            cocov.IssueKindStyle,
	"ioutilDeprecated":      cocov.IssueKindStyle,
	"methodExprCall":        cocov.IssueKindStyle,
	"nestingReduce":         cocov.IssueKindStyle,
	"newDeref":              cocov.IssueKindStyle,
	"octalLiteral":          cocov.IssueKindStyle,
	"paramTypeCombine":      cocov.IssueKindStyle,
	"preferFilepathJoin":    cocov.IssueKindStyle,
	"ptrToRefParam":         cocov.IssueKindStyle,
	"redundantSprint":       cocov.IssueKindStyle,
	"regexpMust":            cocov.IssueKindStyle,
	"regexpSimplify":        cocov.IssueKindStyle,
	"ruleguard":             cocov.IssueKindStyle,
	"singleCaseSwitch":      cocov.IssueKindStyle,
	"sloppyLen":             cocov.IssueKindStyle,
	"stringConcatSimplify":  cocov.IssueKindStyle,
	"switchTrue":            cocov.IssueKindStyle,
	"timeExprSimplify":      cocov.IssueKindStyle,
	"tooManyResultsChecker": cocov.IssueKindStyle,
	"typeAssertChain":       cocov.IssueKindStyle,
	"typeDefFirst":          cocov.IssueKindStyle,
	"typeSwitchVar":         cocov.IssueKindStyle,
	"typeUnparen":           cocov.IssueKindStyle,
	"underef":               cocov.IssueKindStyle,
	"unlabelStmt":           cocov.IssueKindStyle,
	"unlambda":              cocov.IssueKindStyle,
	"unnamedResult":         cocov.IssueKindStyle,
	"unnecessaryBlock":      cocov.IssueKindStyle,
	"unslice":               cocov.IssueKindStyle,
	"valSwap":               cocov.IssueKindStyle,
	"whyNoLint":             cocov.IssueKindStyle,
	"wrapperFunc":           cocov.IssueKindStyle,
	"yodaStyleExpr":         cocov.IssueKindStyle,

	// Current go-critic classification: Performance
	"appendCombine":      cocov.IssueKindPerformance,
	"equalFold":          cocov.IssueKindPerformance,
	"hugeParam":          cocov.IssueKindPerformance,
	"indexAlloc":         cocov.IssueKindPerformance,
	"preferDecodeRune":   cocov.IssueKindPerformance,
	"preferFprint":       cocov.IssueKindPerformance,
	"preferStringWriter": cocov.IssueKindPerformance,
	"preferWriteByte":    cocov.IssueKindPerformance,
	"rangeExprCopy":      cocov.IssueKindPerformance,
	"rangeValCopy":       cocov.IssueKindPerformance,
	"sliceClear":         cocov.IssueKindPerformance,
	"stringXbytes":       cocov.IssueKindPerformance,
}
